changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - github-actions
      - dependabot
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - semver-major
    - title: Features
      labels:
        - enhancement
        - feature
        - semver-minor
    - title: Fixes
      labels:
        - bug
        - fix
        - semver-patch
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - dependencies
        - ci
        - maintenance
    - title: Other Changes
      labels:
        - "*"
