from pathlib import Path


def test_core_research_structure_exists() -> None:
    root = Path(__file__).resolve().parents[1]
    for relative in (
        "AGENTS.md",
        "configs/default.yaml",
        "configs/capabilities.yaml",
        "docs/agent/capability-profile.md",
        "docs/agent/output-contracts.md",
        "docs/agent/project-quality.md",
        "docs/agent/repo-migration-playbook.md",
        "docs/reproducibility/commands.md",
        "scripts/README.md",
        "notebooks/README.md",
        "outputs/figures",
        "outputs/tables",
        "data/raw",
        "analysis_outputs",
        "analysis_outputs/claim-audit.md",
        "artifacts/cache",
        "artifacts/data",
        "artifacts/models",
        "artifacts/releases",
        "artifacts/badge-evidence-ledger.csv",
        "experiments/campaigns/autonomous-campaign-template.md",
        "experiments/campaigns/frontier-results.tsv",
        "repro_outputs/SUMMARY.md",
        "repro_outputs/COMMANDS.md",
        "repro_outputs/LOG.md",
        "repro_outputs/PATCHES.md",
        "repro_outputs/status.json",
        "sources/markdown-linear",
        "sources/source-ledger.csv",
        "sources/zotero/README.md",
        "sources/zotero/import-log.csv",
        "sources/zotero/collection-map.csv",
        "sota/reading-log.csv",
        "sota/citation-chasing-log.csv",
        "sota/literature-matrix.csv",
        "sota/sota-claim-ledger.csv",
        "sota/promotion-rules.md",
        "sota/paper-syntheses",
        "reports/paper/sota-survey.tex",
        "wiki/index.md",
        "wiki/log.md",
        "wiki/templates/source-page.md",
        "wiki/templates/claim-page.md",
        "wiki/templates/experiment-page.md",
        "wiki/templates/decision-record.md",
        "wiki/templates/reviewer-concern.md",
        "wiki/templates/research-question.md",
    ):
        assert (root / relative).exists()
